version: '2.2'

services:
    broker:
        image: camunda/zeebe:0.3.0
        container_name: zeebe-broker
        restart: "on-failure"
        hostname: zeebe-broker

    worker:
        build: .
        command: "zeebe-broker:51015"
